#!/bin/bash

# Usage
function usage() {
  cat << EOS >&2
Usage: trivy kubectl [-h,--help] TYPE NAME [TRIVY OPTION]
 A Trivy plugin that scans the images of a kubernetes resource.

Options:
  -h, --help    Show usage.

Examples:
  # Scan a Pod
  trivy kubectl pod mypod

  # Scan a Deployment
  trivy kubectl deployment mydeployment -n mynamespace

  # Scan a Job and filter by severity
  trivy kubectl job myjob -n mynamespace -- --severity CRITICAL
EOS
  exit
}

function test() {
  echo "Testing ECHO!"
}

